const fs = require('fs');

let adminContent = fs.readFileSync('pages/admin.jsx', 'utf8');
const searchAdmin = '                        <div>\n                          <label className=\"mb-2 block font-urbanist text-sm font-bold text-gray-700\">Location</label>\n                          <input type=\"text\" placeholder=\"E.g. NY Office\" value={newMemberDetails.location} onChange={(e) => setNewMemberDetails({...newMemberDetails, location: e.target.value})} className=\"w-full rounded-xl border border-gray-200 bg-[#FDFBF7] px-4 py-3 font-urbanist text-sm text-primary-color shadow-sm focus:border-secondary-color focus:outline-none focus:ring-1 focus:ring-secondary-color\" />\n                        </div>\n                        <div>\n                          <label className=\"mb-2 block font-urbanist text-sm font-bold text-gray-700\">Registration</label>\n                          <input type=\"text\" placeholder=\"E.g. #12345\" value={newMemberDetails.registration} onChange={(e) => setNewMemberDetails({...newMemberDetails, registration: e.target.value})} className=\"w-full rounded-xl border border-gray-200 bg-[#FDFBF7] px-4 py-3 font-urbanist text-sm text-primary-color shadow-sm focus:border-secondary-color focus:outline-none focus:ring-1 focus:ring-secondary-color\" />\n                        </div>\n                        <div className=\"sm:col-span-2\">\n                          <label className=\"mb-2 block font-urbanist text-sm font-bold text-gray-700\">Certifications</label>\n                          <input type=\"text\" placeholder=\"Comma separated\" value={newMemberDetails.certifications} onChange={(e) => setNewMemberDetails({...newMemberDetails, certifications: e.target.value})} className=\"w-full rounded-xl border border-gray-200 bg-[#FDFBF7] px-4 py-3 font-urbanist text-sm text-primary-color shadow-sm focus:border-secondary-color focus:outline-none focus:ring-1 focus:ring-secondary-color\" />\n                        </div>\n                        <div className=\"sm:col-span-2\">\n                          <label className=\"mb-2 block font-urbanist text-sm font-bold text-gray-700\">Experience</label>\n                          <input type=\"text\" placeholder=\"E.g. 10 years\" value={newMemberDetails.experience} onChange={(e) => setNewMemberDetails({...newMemberDetails, experience: e.target.value})} className=\"w-full rounded-xl border border-gray-200 bg-[#FDFBF7] px-4 py-3 font-urbanist text-sm text-primary-color shadow-sm focus:border-secondary-color focus:outline-none focus:ring-1 focus:ring-secondary-color\" />\n                        </div>';
if (adminContent.includes(searchAdmin)) {
  fs.writeFileSync('pages/admin.jsx', adminContent.replace(searchAdmin, ''));
} else {
  console.log('Could not find those exact lines in admin.jsx!');
}

let editContent = fs.readFileSync('pages/admin/edit/[slug].jsx', 'utf8');
const searchEdit = '                  <div>\n                    <label className=\"mb-2 block font-urbanist text-sm font-bold text-gray-700\">Location</label>\n                    <input type=\"text\" placeholder=\"E.g. NY Office\" value={memberDetails.location} onChange={(e) => setMemberDetails({...memberDetails, location: e.target.value})} className=\"w-full rounded-xl border border-gray-200 bg-[#FDFBF7] px-4 py-3 font-urbanist text-sm text-primary-color shadow-sm focus:border-secondary-color focus:outline-none focus:ring-1 focus:ring-secondary-color\" />\n                  </div>\n                  <div>\n                    <label className=\"mb-2 block font-urbanist text-sm font-bold text-gray-700\">Registration</label>\n                    <input type=\"text\" placeholder=\"E.g. #12345\" value={memberDetails.registration} onChange={(e) => setMemberDetails({...memberDetails, registration: e.target.value})} className=\"w-full rounded-xl border border-gray-200 bg-[#FDFBF7] px-4 py-3 font-urbanist text-sm text-primary-color shadow-sm focus:border-secondary-color focus:outline-none focus:ring-1 focus:ring-secondary-color\" />\n                  </div>\n                  <div className=\"sm:col-span-2\">\n                    <label className=\"mb-2 block font-urbanist text-sm font-bold text-gray-700\">Certifications</label>\n                    <input type=\"text\" placeholder=\"Comma separated\" value={memberDetails.certifications} onChange={(e) => setMemberDetails({...memberDetails, certifications: e.target.value})} className=\"w-full rounded-xl border border-gray-200 bg-[#FDFBF7] px-4 py-3 font-urbanist text-sm text-primary-color shadow-sm focus:border-secondary-color focus:outline-none focus:ring-1 focus:ring-secondary-color\" />\n                  </div>\n                  <div className=\"sm:col-span-2\">\n                    <label className=\"mb-2 block font-urbanist text-sm font-bold text-gray-700\">Experience</label>\n                    <input type=\"text\" placeholder=\"E.g. 10 years\" value={memberDetails.experience} onChange={(e) => setMemberDetails({...memberDetails, experience: e.target.value})} className=\"w-full rounded-xl border border-gray-200 bg-[#FDFBF7] px-4 py-3 font-urbanist text-sm text-primary-color shadow-sm focus:border-secondary-color focus:outline-none focus:ring-1 focus:ring-secondary-color\" />\n                  </div>';

if (editContent.includes(searchEdit)) {
  fs.writeFileSync('pages/admin/edit/[slug].jsx', editContent.replace(searchEdit, ''));
} else {
  console.log('Could not find those exact lines in edit/[slug].jsx!');
}
